### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by nocturni** [SirSquidly/Oceanic-Expanse#1]
Pure forge server, seems like the crash is related to the Clam

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_70016_h(DDD)V
	at com.sirsquidly.oe.entity.EntityClam.func_70071_h_(EntityClam.java:135)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by SirSquidly** [comment]
Can I get the full changelog and forge version?

EDIT: Testing I see the issue is from using setVelocity. I'll change this right now.

**Comment by SirSquidly** [comment]
Fixed this in development builds, changing setVelocity to instead directly alter motionY for targeted entity.

Expect a bugfix update containing the fix later today.

EDIT: 1.0.2 is uploaded with the fix for this issue.
