### ISSUE TITLE
Conduit Charm causes Player to be kicked on server

### ISSUE THREAD

**Issue by SirSquidly** [SirSquidly/Oceanic-Expanse#108]
Attempting to use the Conduit Charm on a Server causes the user to be kicked.

Steps To Reproduce:

1. Join a Multiplayer server with Oceanic Expanse, both on Client and Server
2. Hold the Conduit Charm Item
3. Enter Water

Additionally, checking the server console, this occurs immediately upon the client being disconnected:

<details>
  <summary>Server Log Snippet</summary> 
  
````
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:500) ~[EntityPlayerMP.class:?]
	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:185) ~[NetHandlerPlayServer.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:212) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307) ~[NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:197) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:415) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.NoSuchMethodError: com.sirsquidly.oe.items.ItemCharm.spawnParticles(Lnet/minecraft/world/World;Lnet/minecraft/entity/Entity;)V
	at com.sirsquidly.oe.items.ItemCharm.grantConduit(ItemCharm.java:69) ~[ItemCharm.class:?]
	at com.sirsquidly.oe.items.ItemCharm.onUpdate(ItemCharm.java:47) ~[ItemCharm.class:?]
	at net.minecraft.item.ItemStack.updateAnimation(ItemStack.java:603) ~[ItemStack.class:?]
	at net.minecraft.entity.player.InventoryPlayer.decrementAnimations(InventoryPlayer.java:405) ~[InventoryPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:575) ~[EntityPlayer.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2405) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:272) ~[EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:423) ~[EntityPlayerMP.class:?]
	... 9 more
````  
</details>

This is caused by `spawnParticles()` being Clientside Only, but being called at [Line 69](https://github.com/SirSquidly/Oceanic-Expanse/blob/f392c4662703bb0a9289355e43f95deab5cb671e/src/main/java/com/sirsquidly/oe/items/ItemCharm.java#L69) without checking if the world is remote.

Should be a very quick fix.

**Comment by SirSquidly** [comment]
Partially fixed in 1.1.5

They no longer cause the client to get kicked, but don't properly spawn in particles for other clients. This will require a little more investigation, but should be considered a separate issue from this.
