### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Sixdd6** [SirSquidly/Oceanic-Expanse#31]
Myself and others on my server have noticed a crash issue when right-clicking a bucket of water on the tile we are standing on. I can provide more information if needed.

[latest.log](https://github.com/SirSquidly/Oceanic-Expanse/files/11693051/latest.log)
[crash-2023-06-08_16.01.06-client.txt](https://github.com/SirSquidly/Oceanic-Expanse/files/11693052/crash-2023-06-08_16.01.06-client.txt)

**Comment by SirSquidly** [comment]
This is odd. I'll be honest, I don't own multiple MC accounts, so I don't have any way to test this myself.

I am going to make a guess and hope it's because the checks aren't accounting for `EntityPlayerMP`,as I think it sounds reasonable. I'll put the fix in the next update, and leave with issue open a bit to see if it works out.

**Comment by SirSquidly** [comment]
Added a possible fix in version 1.0.7.

I'm leaving this issue open for a few day, hoping for some feedback. If I get nothing, I'll just close this issue.

**Comment by judgekreep** [comment]
3 people on my dedicated server, including myself, had this crash happen recently.
Each of us right clicked some entity with a bucket; one of the players tried burning a Chicken with a lava bucket.

I did disable some of the mobs from this mod, like the Pufferfish.
I'm thinking EntityList.getKey(entity) is returning null and is probably causing this crash.

Happened with: OE 1.0.7

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-01-28 21:10:30 CST
Description: Unexpected error

java.lang.NullPointerException
    at com.sirsquidly.oe.event.BucketMobEvent.RightClickItem(BucketMobEvent.java:60)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_541_BucketMobEvent_RightClickItem_RightClickItem.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onItemRightClick(ForgeHooks.java:1123)
    at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClick(PlayerControllerMP.java:508)
    at net.optifine.override.PlayerControllerOF.processRightClick(PlayerControllerOF.java:80)
    at net.minecraft.client.Minecraft.rightClickMouse(MinecraftMixin.java:1597)
    at net.minecraft.client.Minecraft.processKeyBinds(MinecraftMixin.java:2254)
    at net.minecraft.client.Minecraft.runTickKeyboard(MinecraftMixin.java:2020)
    at net.minecraft.client.Minecraft.runTick(MinecraftMixin.java:1808)
    at net.minecraft.client.Minecraft.runGameLoop(MinecraftMixin.java:1098)
    at net.minecraft.client.Minecraft.run(MinecraftMixin.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by SirSquidly** [comment]
Fixes have been implemented in 1.1.0.

If someone else encounters this issue again, please make a new Issue on the tracker!
