### ISSUE TITLE
Conflicting mob ID's with Berries and Mobs Mod

### ISSUE THREAD

**Issue by Fandalf89** [SirSquidly/Oceanic-Expanse#4]
Hello there,
So I recently found out about this interesting mod, love the idea of using this for a vanilla plus modpack, when I was using this mod together with "Berries and Mobs mod" the game crashed, due to a ID conflict, it seems is just the Drowned Mob but I do not know if will happen with other underwater mobs (fish and turtles specially). I hope this issue can be solved. I am pasting the error log.

`[13:30:51] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@645e2cfe:
java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.drowned.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.drowned.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.drowned
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:41) ~[qo.class:?]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.registerStatistics(EntityEntryBuilder.java:285) ~[EntityEntryBuilder.class:?]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.access$100(EntityEntryBuilder.java:57) ~[EntityEntryBuilder.class:?]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.addedToRegistry(EntityEntryBuilder.java:335) ~[EntityEntryBuilder$BuiltEntityEntry.class:?]
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:509) ~[GameData$EntityCallbacks.class:?]
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:500) ~[GameData$EntityCallbacks.class:?]
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:350) ~[ForgeRegistry.class:?]
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281) ~[ForgeRegistry.class:?]
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113) ~[ForgeRegistry.class:?]
	at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154) ~[ForgeRegistry.class:?]
	at net.mcreator.berriesandmobsmod.BerriesAndMobsModMod.registerEntities(BerriesAndMobsModMod.java:101) ~[BerriesAndMobsModMod.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_BerriesAndMobsModMod_registerEntities_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857) [GameData.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_361]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_361]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_361]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_361]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_361]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_361]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_361]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_361]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[13:30:51] [Client thread/ERROR] [FML]: Index: 13 Listeners:
[13:30:51] [Client thread/ERROR] [FML]: 0: NORMAL
[13:30:51] [Client thread/ERROR] [FML]: 1: net.minecraftforge.fml.common.eventhandler.EventBus$1@3f5b2857
[13:30:51] [Client thread/ERROR] [FML]: 2: net.minecraftforge.fml.common.eventhandler.EventBus$1@4e1cc48b
[13:30:51] [Client thread/ERROR] [FML]: 3: net.minecraftforge.fml.common.eventhandler.EventBus$1@530e1f71
[13:30:51] [Client thread/ERROR] [FML]: 4: net.minecraftforge.fml.common.eventhandler.EventBus$1@46a2f032
[13:30:51] [Client thread/ERROR] [FML]: 5: net.minecraftforge.fml.common.eventhandler.EventBus$1@20dd6121
[13:30:51] [Client thread/ERROR] [FML]: 6: net.minecraftforge.fml.common.eventhandler.EventBus$1@84dd12d
[13:30:51] [Client thread/ERROR] [FML]: 7: net.minecraftforge.fml.common.eventhandler.EventBus$1@2b9bb2c2
[13:30:51] [Client thread/ERROR] [FML]: 8: net.minecraftforge.fml.common.eventhandler.EventBus$1@7a69f4e3
[13:30:51] [Client thread/ERROR] [FML]: 9: net.minecraftforge.fml.common.eventhandler.EventBus$1@31f656e6
[13:30:51] [Client thread/ERROR] [FML]: 10: net.minecraftforge.fml.common.eventhandler.EventBus$1@57543d4c
[13:30:51] [Client thread/ERROR] [FML]: 11: net.minecraftforge.fml.common.eventhandler.EventBus$1@21af88c6
[13:30:51] [Client thread/ERROR] [FML]: 12: net.minecraftforge.fml.common.eventhandler.EventBus$1@14d4aefc
[13:30:51] [Client thread/ERROR] [FML]: 13: net.minecraftforge.fml.common.eventhandler.EventBus$1@17969be6
[13:30:51] [Client thread/ERROR] [FML]: 14: net.minecraftforge.fml.common.eventhandler.EventBus$1@615e6a05
[13:30:52] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: UP_TO_DATE Target: null
[13:30:52] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  PCF Core Mod (PhosphorCrashFix-1.12.2-1.0.0.jar)
  RenderLibPlugin (RenderLib-1.12.2-1.2.7.jar)
  PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  Fluidlogged API Plugin (Fluidlogged-API-v2.1.2-mc1.12.2.jar)
  NothiriumPlugin (Nothirium-1.12.2-0.2.4.jar)
  MixinBooter (!mixinbooter-7.0.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 4/11/23 1:30 PM
Description: Initializing game

java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.drowned.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.drowned.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.drowned
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:41)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.registerStatistics(EntityEntryBuilder.java:285)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.access$100(EntityEntryBuilder.java:57)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.addedToRegistry(EntityEntryBuilder.java:335)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:509)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:500)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:350)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154)
	at net.mcreator.berriesandmobsmod.BerriesAndMobsModMod.registerEntities(BerriesAndMobsModMod.java:101)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_BerriesAndMobsModMod_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

(MixinBooter) Mixins in Stacktrace:
	net.minecraft.client.Minecraft:
		me.jellysquid.mods.phosphor.mixins.lighting.client.MixinMinecraft (mixins.phosphor.json)
		meldexun.renderlib.mixin.MixinMinecraft (mixins.renderlib.json)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:41)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.registerStatistics(EntityEntryBuilder.java:285)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.access$100(EntityEntryBuilder.java:57)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.addedToRegistry(EntityEntryBuilder.java:335)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:509)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:500)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:350)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154)
	at net.mcreator.berriesandmobsmod.BerriesAndMobsModMod.registerEntities(BerriesAndMobsModMod.java:101)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_BerriesAndMobsModMod_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_361, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1042349696 bytes (994 MB) / 1302855680 bytes (1242 MB) up to 2386558976 bytes (2276 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2560m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version      | Source                                      | Signature                                |
	|:----- |:-------------------- |:------------ |:------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2       | minecraft.jar                               | None                                     |
	| LCH   | mcp                  | 9.42         | minecraft.jar                               | None                                     |
	| LCH   | FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2859-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2859 | forge-1.12.2-14.23.5.2859-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | mixinbooter          | 7.0          | minecraft.jar                               | None                                     |
	| LCH   | berries_and_mobs_mod | 1            | BerriesAndMobs-1.12.2-1.50.jar              | None                                     |
	| LCH   | fluidlogged_api      | 2.1.2        | Fluidlogged-API-v2.1.2-mc1.12.2.jar         | None                                     |
	| LCH   | renderlib            | 1.2.7        | RenderLib-1.12.2-1.2.7.jar                  | None                                     |
	| LCH   | nothirium            | 0.2.4-beta   | Nothirium-1.12.2-0.2.4.jar                  | None                                     |
	| LCH   | oe                   | 1.0.2        | OceanicExpanse-1.0.2.jar                    | None                                     |
	| LCH   | performant           | 1.12.2-1.5   | Performant-1.11.jar                         | None                                     |
	| LCH   | phosphorcrashfix     | 1.0.0        | PhosphorCrashFix-1.12.2-1.0.0.jar           | None                                     |
	| LCH   | phosphor-lighting    | 1.12.2-0.2.7 | phosphor-forge-mc1.12.2-0.2.7-universal.jar | None                                     |

	Loaded coremods (and transformers): 
PCF Core Mod (PhosphorCrashFix-1.12.2-1.0.0.jar)
  nathan.phosphorcrashfix.patches.PhosphorSlicePatch
RenderLibPlugin (RenderLib-1.12.2-1.2.7.jar)
  meldexun.renderlib.asm.RenderLibClassTransformer
PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  
Fluidlogged API Plugin (Fluidlogged-API-v2.1.2-mc1.12.2.jar)
  git.jbredwards.fluidlogged_api.mod.asm.ASMHandler$Transformer
  git.jbredwards.fluidlogged_api.mod.asm.transformers.TransformerLevelProperty
  git.jbredwards.fluidlogged_api.mod.asm.transformers.TransformerSmoothWater
NothiriumPlugin (Nothirium-1.12.2-0.2.4.jar)
  meldexun.nothirium.mc.asm.NothiriumClassTransformer
MixinBooter (!mixinbooter-7.0.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8280' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.6.0 - Build 27.20.100.8280, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Vanilla-Future-Texture-v11.2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8280
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4
[13:30:52] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed!`

So far this was the only issue. Looking forward for mod updates! Keep up the lovely work!

**Comment by SirSquidly** [comment]
This is extremely odd, as this issue is only really with Berries and Mobs and my mod.

For example, Oceanic Expanse, Future MC, and Subaquatic all work together, despite this adding 3 cods, 3 salmon, 3 tropical fish, and ect all with the exact same names.

I am spending some time to further investigate this issue.

**Comment by SirSquidly** [comment]
My current belief is that Berries and Mobs doesn't properly set its entity IDs, leading to Forge seeing it as a duplicate.

I cannot check this, as Berries and Mobs is closed source currently. 

I am predicting this as your log shows Forge is catching a duplicate ID while registering Berries and Mobs, which is not an issue for other mods such as FutureMC or Subaquatic, which also have entities with the same names as Oceanic Expanse.

**Comment by SirSquidly** [comment]
Actually, deepest apologies, further investigating shows _I am also_ registering entities improperly! I should have added my ModID to the registry name!

Expect a bugfix very soon.

**Comment by SirSquidly** [comment]
Fixed this in Version 1.0.3.

For future reference, the issue was due to both of our mods not set a unique EntityName. I fixed it on my end, although to avoid any future issues Berries and Mobs should also set unique EntityNames.
