### ISSUE TITLE
crash after some time

### ISSUE THREAD

**Issue by ralseilii** [SirSquidly/Oceanic-Expanse#45]
when download ocean expanse 1.0.7 my game often crashes after sometime and the crash report is spawning ticking issue that
"Description: Exception ticking world

java.lang.NullPointerException
    at com.sirsquidly.oe.event.InjectAIEvent.spawnEvent(InjectAIEvent.java:59)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1211_InjectAIEvent_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.world.World.func_72838_d(World.java:1209)
    at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
    at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:248)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)"
note:
i have downloaded Nothirium , newest version of ImprovableSkills ,HammerLib and biome o plenty ， censoredasm5.6 ,!mixinbooter-8.6.

will u help fix that crash bug , the ocean expanse is just 1.12.2 players need for ocean

**Comment by ralseilii** [comment]
i also downloaded newest version of ImprovableSkills and HammerLib ,maybe that causes some spawning issue

**Comment by ralseilii** [comment]
it crash whenever the game lags for some seconds ,  without ocean expanse it game just lags for some seconds and then become normal

**Comment by ralseilii** [comment]
the crash did not happen in 1.0.5 version but happen in 1.0.6 and 1.0.7

**Comment by ralseilii** [comment]
i think it is caused by drowned , because when i disable it in config , the game does not crash anymore

**Comment by ralseilii** [comment]
it is not caused by drowned,as i disable it from config, the game still crashes after some time

**Comment by ralseilii** [comment]
when fps is low,the game crashes(i have fps reducer and when game is in background)
