### ISSUE TITLE
Crash on join

### ISSUE THREAD

**Issue by Sereath** [SirSquidly/Oceanic-Expanse#59]
I know ticking world crashes can be a pain but this happened to me once, when loading a new world
and right after updating to Future MC from 0.2.15 to 0.2.19. Which makes me wonder.

https://gist.github.com/Sereath/f0ef909b776e57e39fd867290ed1f9c8
```
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
    at com.sirsquidly.oe.event.InjectAIEvent.spawnEvent(InjectAIEvent.java:59)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1618_InjectAIEvent_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.world.World.spawnEntity(World.java:1209)
    at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1058)
    at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:248)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:203)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```

Hasn't happened again when joining other new worlds.

**Comment by Sereath** [comment]
Oh, seems to be this:
https://github.com/thedarkcolour/Future-MC/issues/352

Which is still odd because I had already disabled Future MC fish.

**Comment by Robolightning** [comment]
> Oh, seems to be this: [thedarkcolour/Future-MC#352](https://github.com/thedarkcolour/Future-MC/issues/352)
> 
> Which is still odd because I had already disabled Future MC fish.

I have the same issue. How to fix this? I read on some Chinese forums that the promlem is in turtle. Is it right?
Full crash report:
[crash-2024-04-21_04.10.26-server.txt](https://github.com/SirSquidly/Oceanic-Expanse/files/15050337/crash-2024-04-21_04.10.26-server.txt)
[2024-04-21-6.log.gz](https://github.com/SirSquidly/Oceanic-Expanse/files/15050342/2024-04-21-6.log.gz)
[debug-2.log.gz](https://github.com/SirSquidly/Oceanic-Expanse/files/15050343/debug-2.log.gz)

**Comment by SirSquidly** [comment]
I am almost certain this was due to some edge-case being caused by my usage of ArrayUtils.

ArrayUtils isn't _ever_ supposed to return Null, yet it does. So, I tried ripping ANY use of it out.

Hopefully it fixes this reoccurring issue.
