### ISSUE TITLE
Conflict with Capsule results in a crash.

### ISSUE THREAD

**Issue by Handeril** [SirSquidly/Oceanic-Expanse#7]
This is the error, as my latest.log won't post and there's no crash report:

This instantly freezes the game upon right-clicking the "one use" capsule, and I can assume the error carries over to other caspules as well. (Which happened for the first time while I was showing a feature of my modpack.) Thank you for your time.

[12:28:22] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickItem@2d5e758f:
java.lang.NullPointerException: null
	at com.sirsquidly.oe.event.BucketMobEvent.RightClickItem(BucketMobEvent.java:59) ~[BucketMobEvent.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1921_BucketMobEvent_RightClickItem_RightClickItem.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onItemRightClick(ForgeHooks.java:1123) [ForgeHooks.class:14.23.5.2860]
	at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClick(PlayerControllerMP.java:508) [bsa.class:?]
	at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1597) [bib.class:?]
	at net.minecraft.client.Minecraft.redirect$zdb000$onDoItemUse(Minecraft.java:3375) [bib.class:?]
	at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2254) [bib.class:?]
	at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2020) [bib.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808) [bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:6614) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[12:28:22] [Client thread/ERROR]: Index: 11 Listeners:
[12:28:22] [Client thread/ERROR]: 0: HIGHEST
[12:28:22] [Client thread/ERROR]: 1: ASM: class thecodex6824.thaumicaugmentation.common.event.MorphicEventHandler onPlayerInteractRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 2: ASM: com.oitsjustjose.tinkers_addons.modifiers.ModAutoRepair@79d03d2 onUpdate(Lnet/minecraftforge/event/entity/player/PlayerEvent;)V
[12:28:22] [Client thread/ERROR]: 3: HIGH
[12:28:22] [Client thread/ERROR]: 4: ASM: class com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesPlayerEventHandler onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 5: ASM: class codersafterdark.reskillable.base.LevelLockHandler rightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 6: ASM: moretweaker.mob_grinding_utils.SpawnEggHandler@33681fe2 living(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
[12:28:22] [Client thread/ERROR]: 7: NORMAL
[12:28:22] [Client thread/ERROR]: 8: ASM: class WayofTime.bloodmagic.util.handler.event.GenericHandler onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 9: ASM: class com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesPlayerEventHandler onRightClickItemLog(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 10: ASM: class com.sirsquidly.oe.event.BucketWaterEvent RightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 11: ASM: class com.sirsquidly.oe.event.BucketMobEvent RightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 12: ASM: class thecodex6824.thaumicaugmentation.common.event.AugmentEventHandler onInteractAir(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 13: ASM: class mrthomas20121.tinkers_reforged.library.trait.TraitManager onItemRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 14: ASM: class com.windanesz.ancientspellcraft.item.ItemTransmutationScroll onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 15: ASM: class com.windanesz.ancientspellcraft.handler.ASEventHandler onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 16: ASM: crafttweaker.mc1120.events.CommonEventHandler@2b1572 onPlayerRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 17: ASM: class team.chisel.common.item.ChiselController onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 18: ASM: vazkii.quark.decoration.feature.PlaceBlazeRods@3d0d38cc onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 19: ASM: vazkii.quark.misc.feature.PlaceVanillaDusts@690baf52 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 20: ASM: vazkii.quark.misc.feature.MapMarkers@52c32f69 rightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 21: ASM: vazkii.quark.misc.feature.ThrowableDragonBreath@136b3b8b playerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 22: ASM: vazkii.quark.misc.feature.ReacharoundPlacing@52d1d724 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 23: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@63f501be onEntityUseItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 24: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@63f501be onEntityRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 25: ASM: INSTANCE onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 26: ASM: pegbeard.dungeontactics.handlers.DTEventHandler@33bfd97e onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 27: ASM: mods.railcraft.common.fluids.CustomContainerHandler@76e85534 onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 28: ASM: mcjty.rftools.ForgeEventHandlers@30d2a186 onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 29: ASM: net.silentchaos512.lib.event.SilentLibCommonEvents@5f0ef1d8 onPlayerRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 30: ASM: com.sosnitzka.taiga.traits.TraitTantrum@174e718e rightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 31: ASM: com.sosnitzka.taiga.traits.TraitCatcher@2e588c2f onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 32: ASM: com.sosnitzka.taiga.traits.TraitPorted@76813096 onItemRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 33: ASM: com.sosnitzka.taiga.traits.TraitWhirl@586d0939 onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 34: ASM: com.sosnitzka.taiga.traits.TraitBerserk@33da4c25 onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 35: ASM: com.existingeevee.moretcon.traits.unique.BloodyArc@65ead39f onMouseClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 36: ASM: fi.dy.masa.tellme.event.InteractEventHandler@51ca1299 onRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 37: ASM: de.ellpeck.actuallyadditions.mod.items.ItemWaterBowl@5527c741 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 38: ASM: class com.rwtema.careerbees.effects.EffectFoodModify onStartEat(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 39: ASM: class thebetweenlands.common.item.tools.ItemGreatsword onStartUsingItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 40: ASM: com.tfar.randomenchants.util.EventHandler@102daf4a toggle(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 41: ASM: xzeroair.trinkets.events.EventHandler@715bf91d playerRightClickItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 42: ASM: de.teamlapen.vampirism.player.ModPlayerEventHandler@13898282 onItemRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/ERROR]: 43: ASM: class electroblob.wizardry.spell.Transience onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 44: ASM: class electroblob.wizardry.spell.Possession onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 45: ASM: class electroblob.wizardry.entity.construct.EntityForcefield onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 46: ASM: class WayofTime.bloodmagic.util.handler.event.GenericHandler onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 47: ASM: class WayofTime.bloodmagic.util.handler.event.LivingArmourHandler onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 48: ASM: class com.tfar.randomenchants.ench.enchantment.EnchantmentHooked playerTick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 49: ASM: class com.tfar.randomenchants.ench.enchantment.EnchantmentGrappling playerTick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 50: ASM: class wile.rsgauges.ModRsGauges$RegistrationSubscriptions playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 51: ASM: class com.windanesz.ancientspellcraft.entity.construct.EntityArcaneBarrier onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 52: ASM: crafttweaker.mc1120.events.CommonEventHandler@2b1572 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 53: ASM: net.darkhax.itemstages.ItemStages@554ca6cf onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 54: ASM: class it.hurts.metallurgy_reforged.handler.EffectHandler onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 55: ASM: Block{minecraft:air} interact(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 56: ASM: lumien.randomthings.handler.RTEventHandler@1970ac61 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 57: ASM: mcjty.rftools.ForgeEventHandlers@30d2a186 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 58: ASM: appeng.parts.PartPlacement@7b1b852d playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 59: ASM: com.lothrazar.cyclicmagic.playerupgrade.PlayerAbilitiesModule@3c0a7515 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 60: ASM: ca.glasspelican.loginshield.loginshield@5acb6624 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 61: ASM: class thebetweenlands.common.handler.ItemEquipmentHandler onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 62: ASM: class thebetweenlands.common.handler.PuppetHandler onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 63: ASM: xzeroair.trinkets.events.EventHandler@715bf91d playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 64: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@559ff909 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:28:22] [Client thread/ERROR]: 65: ASM: class it.hurts.metallurgy_reforged.handler.EffectHandler livingEvent(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
[12:28:22] [Client thread/ERROR]: 66: ASM: mob_grinding_utils.events.ChickenFuseEvent@6f1b7250 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
[12:28:22] [Client thread/ERROR]: 67: LOW
[12:28:22] [Client thread/ERROR]: 68: ASM: levelup2.event.CraftingSkillHandler@489eec88 onFishInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
[12:28:22] [Client thread/WARN]: Failed to identify net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1921_BucketMobEvent_RightClickItem_RightClickItem (untransformed name: net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1921_BucketMobEvent_RightClickItem_RightClickItem)

**Comment by SirSquidly** [comment]
I am unable to replicate this issue.

Please ensure you are using the latest version of the mod (1.0.4 as of time of writing), as this exactly matches an issue fixed in 1.0.3

**Comment by Handeril** [comment]
We have a new issue now, I can't seem to activate the capsules at all. When I right click, they just "tick" the item, not activating at all.

It's better than crashing, now it's just a matter of figuring out how to fix this so capsules can activate and be used again.
