### ISSUE TITLE
Bug with partying

### ISSUE THREAD

**Issue by marsovar** [SirSquidly/Oceanic-Expanse#85]
Hello im new to github but i would like to share an issue , on my server, the crab partying event is making crash 

Time: 6/22/24 1:16 PM
Description: Ticking entity

java.lang.NoSuchMethodError: com.sirsquidly.oe.entity.EntityCrab.isPartying()Z
	at com.sirsquidly.oe.entity.EntityCrab.func_70636_d(EntityCrab.java:170)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by marsovar** [comment]
i forgot to tell its on the 1.12.2 version

**Comment by SirSquidly** [comment]
As mentioned on https://github.com/SirSquidly/Oceanic-Expanse/issues/88#issuecomment-2233837113, this is likely a code oversight on my part.

**Comment by SirSquidly** [comment]
Fixed in 1.1.3
